### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by luqmaan** [luqmaan/Instabus#180]
- [ ] Bring more content above the fold
- [ ] Update old screenshots
- [ ] Update contributors

**Comment by fleeting** [comment]
For contributors it's easier to list the primary people and then just link off to https://github.com/luqmaan/Instabus/graphs/contributors for the rest. Examples at the bottom of http://movethewebforward.org/ and http://html5please.com/.

**Comment by luqmaan** [comment]
Fixed in #219
