### ISSUE TITLE
Generate static GTFS data for all the routes

### ISSUE THREAD

**Issue by luqmaan** [luqmaan/Instabus#185]
:cat:

**Comment by scascketta** [comment]
Something that might help with checking some of the new routes is the [transitfeed](https://github.com/google/transitfeed) library, particularly the [FeedValidator](https://github.com/google/transitfeed/wiki/FeedValidator) and [ScheduleViewer](https://github.com/google/transitfeed/wiki/ScheduleViewer#running-from-source). I've been using the ScheduleViewer to get a better idea of how different trips for a route will look.
