### ISSUE TITLE
Display add to Home Screen popup

### ISSUE THREAD

**Issue by luqmaan** [luqmaan/Instabus#192]
After the 1st day, 15% of users never return. After a week, 5% of users return.

Adding the app to their home screen seems like a good way to make people remember Instabus exists.

![screen shot 2015-03-05 at 11 56 12 am](https://cloud.githubusercontent.com/assets/1275831/6511421/62f94334-c332-11e4-94fc-02707e045c09.png)

**Comment by gtilma** [comment]
Would you be open to integrating something like [this from cubiq](https://github.com/cubiq/add-to-homescreen)?

**Comment by luqmaan** [comment]
Yes! Although cubiq looks like its bower only. :(

Is there an equivalent on npm?

**Comment by gtilma** [comment]
No, at least as far as I can tell. If I have time I'll try to roll my own though. Btw, love the app.

**Comment by luqmaan** [comment]
Rolling your own sounds great. Glad Instabus is useful for you.

**Comment by luqmaan** [comment]
Also, it wouldn't be the end of the world to add bower, but you'd need to take care of adding it to `gulp build` and such.

**Comment by luqmaan** [comment]
For Android, maybe just do this? http://updates.html5rocks.com/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android#criteria

**Comment by gtilma** [comment]
Looks like a good option. Haven't had much time lately, but would love to contribute when I have the chance.
