### ISSUE TITLE
arrival times in popup need directionals

### ISSUE THREAD

**Issue by joshmadewell** [luqmaan/Instabus#197]
I think this is only an issue with the train because both directions share the same stop id but we need to specify if an arrival time at a stop is for north or south bound

**Comment by luqmaan** [comment]
Got a PR? ;)

**Comment by joshmadewell** [comment]
I don't right now :/ been pretty busy, I might be able to throw something
together this weekend though.

On Fri, Mar 13, 2015 at 9:43 AM, Luqmaan Dawoodjee <notifications@github.com

**Comment by scascketta** [comment]
Added this on branch `show-me-the-way`, but I'm not sure where is best to display the direction. For now it's next to the time enclosed in parens. Do we need this?

**Comment by joshmadewell** [comment]
That's where I would have put it. I think is needed only for the train.

**Comment by luqmaan** [comment]
Fixed for now. We really need to redesign the UI so this issue can't exist.
