### ISSUE TITLE
Save favorite routes

### ISSUE THREAD

**Issue by ryannorton** [luqmaan/Instabus#209]
Most commuters take the same buses every day. It would be nice to be able to save all your favorite routes and then see all of them at once when you visit instabus.

**Comment by luqmaan** [comment]
What sort of UI makes sense for this?

Maybe something like this?

![image](https://cloud.githubusercontent.com/assets/1275831/7170909/e799e974-e397-11e4-89b1-607e4c954aae.png)

**Comment by ryannorton** [comment]
Me gusta. Another idea is to let users make route groups. For example, there's a particular set of buses that I care about when going from home to work, then a different set of buses for work to home, etc.

**Comment by luqmaan** [comment]
Custom route groups sounds complex to setup.

Forgot about the `Nearby Routes` section that we can add if we implement #206:

![image](https://cloud.githubusercontent.com/assets/1275831/7171543/61f7d954-e39f-11e4-995e-82d2b15cb86b.png)

**Comment by jpmensching** [comment]
@luqmaan I've submitted https://github.com/luqmaan/Instabus/pull/212 for this issue. By the way, this is a great project and I'm looking forward to helping out more!

**Comment by luqmaan** [comment]
:bus: Implemented in #212

**Comment by jpmensching** [comment]
Comments addressed in https://github.com/luqmaan/Instabus/pull/213.
