### ISSUE TITLE
Get user feedback via survey

### ISSUE THREAD

**Issue by betsydupuis** [luqmaan/Instabus#211]
I guess this would need to be a pop-up.
Say something like...
"Do you want to help make Instabus better?" **Take our survey ->**

**Feedback areas of interest**
* Usecases
* Context that instabus is used
* Most frequently used information
* Information that is currently difficult to find.
* etc...

**Comment by luqmaan** [comment]
What other transit applications do you use? (Google Maps, Transit App, etc.)

What do you think is missing from Instabus?

How accurate are the vehicle positions?

How accurate are the estimated times?

Do you prefer using the vehicle positions or prefer using the estimates?

How often do you use Instabus?

What route(s) do you use Instabus for?

**Comment by itsjustluck** [comment]
Awesome, those are all great questions.

Here are some more.

When search for a stop or route... I'm usually looking for 
a) Stops on my usual route
b) New routes near me
c) I use both of these features frequently.
d) Other
