### ISSUE TITLE
Route View shows buses for both directions.

### ISSUE THREAD

**Issue by betsydupuis** [luqmaan/Instabus#215]
Example: You see both northbound buses and southbound buses on a northbound route.

**Comment by luqmaan** [comment]
Is this a feature or a bug? :trollface:

**Comment by itsjustluck** [comment]
That's up to you I think. =P

If it is a feature, it was mentioned to me by a user as an unexpected behavior. He showed it to me on his phone, and it really crowds the screen.

I looked into the code in rappid.js:
```
this.vehicles = new VehicleCollection(route.id(), route.directionId());
```
This looks like it should be creating collections based on direction id.

So... when I go the console in the route view...

![screen shot 2015-09-21 at 9 24 58 am](https://cloud.githubusercontent.com/assets/2096627/9994407/ae524058-6042-11e5-9fd9-8d27374ba776.png)

Based on the mock data, I'm expecting a direction code (N, W, S, E), but that's about as far as I got on that.
